CREATE TABLE TB_PESSOA (
    id   INTEGER      NOT NULL AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL,
    cpf  VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE TB_ENDERECO(
    id   INTEGER      NOT NULL AUTO_INCREMENT,
    rua VARCHAR(128) NOT NULL,
    cep  VARCHAR(128),
    PRIMARY KEY (id)
);

